language: common-lisp
sudo: required

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=release
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl
    - LISP=allegro
    - LISP=cmucl

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh

script:
  # prove-asdf must be independent.
  - ros +Q -l prove-asdf.asd -e '(asdf:load-system :prove-asdf)'
  - ros -l prove.asd -e '(ql:quickload :prove)'
  - ros -l cl-test-more.asd -e '(ql:quickload :cl-test-more)'
